- .gitignore
Added a couple of entries to cover all matches in the .gitignore on BB Learn
> Update .gitignore to match course files

- Java-Project-Management/src/ngo_2024/Stad.java
Utkast till en Stad-klass. Något att utgå ifrån i en diskussion om hur vi ska lägga upp det rent allmänt. Inte en färdig klass.
> Stad-klass. Något att utgå ifrån i diskussionen.

- Java-Project-Management/src/ngo_2024/Partner.java
Första version, finns en del kommenterat som kan uppdateras framöver (ex en extra konstruktor, evt onödig)
Ingen verifikation av input, ligger bortkommenterade början på sådana men inget riktigt än
I kravspec efterfrågas att kunna ta bort info - här finns metod för att ta bort all info om en partner (via DELETE) men som jag förstått är enda sättet att få bort info i en cell att sätta det som null - något vi vill titta närmare på framöver säkert, eller med instruktioner?
> Partner-klass

- Java-Project-Management/src/ngo_2024/Anstalld.java
- Java-Project-Management/src/ngo_2024/Stad.java
En första version av Anställd-klassen.
> Anstalld klass

- Java-Project-Management/src/ngo_2024/Handlaggare.java
- Java-Project-Management/src/ngo_2024/Stad.java
Ett utkast till klassen Handläggare som utökar klassen Anställd.
> Handläggare klass

- Java-Project-Management/src/ngo_2024/Projekt.java
- Java-Project-Management/src/ngo_2024/Validering.java
Projekt-klassen
Validerings-klassen har fått tre nya metoder för validering av korrekt datumformatering vid inmatning. 
- de två metoder datumFöreKontroll och datumEfterKontroll behöver kombineras med ex SQL-query för att få ett datum att utgå från i jämförelsen. Praktisk applikation är att sätta start och slutdatum på projekt som inte är fel i time-space continuum.
> Projekt dev

- Java-Project-Management/src/ngo_2024/Anstalld.java
- Java-Project-Management/src/ngo_2024/Handlaggare.java
> Handläggare uppdaterad

- Java-Project-Management/src/ngo_2024/Huvudmeny.form
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
Fungerande knappar till Avdelningsmenyn
> Uppdaterad med knapp för Avdelning

- Java-Project-Management/src/ngo_2024/EditProjekt.form
- Java-Project-Management/src/ngo_2024/EditProjekt.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.form
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
La till koppling mot huvudmenyn från Administratör - Projekt
Lite småändringar i EditProjekt
> EditProjekt + Huvudmeny-länk

- Java-Project-Management/src/ngo_2024/Anstallda.java
- Java-Project-Management/src/ngo_2024/EditAnstalld.form
- Java-Project-Management/src/ngo_2024/EditAnstalld.java
> Editanstalld

- Java-Project-Management/src/ngo_2024/AvdelningMeny.form
- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/EditAvdelning.java
Adderat Validering i EditAvdelning
QoL-fixar i Avdelning med bättre namn på saker.
> Edit avdelning uppdaterad med validering

- Java-Project-Management/src/ngo_2024/EditHallbarhetsmal.form
- Java-Project-Management/src/ngo_2024/EditHallbarhetsmal.java
- Java-Project-Management/src/ngo_2024/Validering.java
Ny funktion i Validering för comboBoxes. Man skickar in getSelectedItem() (som är ett objekt).
> Lagt till validering för Hållbarhetsmål.

- Java-Project-Management/src/ngo_2024/EditStad.java
> Lagt till validering för EditStad.

- Java-Project-Management/src/ngo_2024/EditLand.form
- Java-Project-Management/src/ngo_2024/EditLand.java
- Java-Project-Management/src/ngo_2024/EditStad.java
Även bytt namn på fältvariabler så de är lättare att hantera.
> Edit land nu med validering

- Java-Project-Management/src/ngo_2024/EditLand.form
- Java-Project-Management/src/ngo_2024/EditLand.java
- Java-Project-Management/src/ngo_2024/LandMeny.form
- Java-Project-Management/src/ngo_2024/LandMeny.java
Ändrat lite i validering för Valuta-fält (som ska vara en double).
Fixat lite buggar i knappar. 
Fixat så att man kan skapa nya land på samma vis som vi gjort med övriga menyer.
> Landuppdateringar

- Java-Project-Management/src/ngo_2024/Huvudmeny.java
Tagit bort aid och ändrat queryAid till private
> Huvudmeny finjusteringar

- Java-Project-Management/src/ngo_2024/EditHallbarhetsmal.form
- Java-Project-Management/src/ngo_2024/EditHallbarhetsmal.java
- Java-Project-Management/src/ngo_2024/HallbarhetsmalMeny.java
* Kommentarer mest av allt.
* Ny Avbryt-knapp.
> Kommenterat upp Hållbarhetsmål

- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/EditAvdelning.form
- Java-Project-Management/src/ngo_2024/EditAvdelning.java
* Kommentarer mest av allt.
* Ny Avbryt-knapp i EditAvdelning.
> Kommenterat upp Avdelning

- Java-Project-Management/src/ngo_2024/AnstalldMeny.java
- Java-Project-Management/src/ngo_2024/EditAnstalld.java
- Java-Project-Management/src/ngo_2024/InloggningMeny.java
Lagt till funktioner i EditAnstalld (kändes som det mest logiska stället).
Mindre justeringar i övrigt i dessa delar.
> Återställl Lösenord

- Java-Project-Management/src/ngo_2024/EditProjektPartner.form
- Java-Project-Management/src/ngo_2024/EditProjektPartner.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.form
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
ta bort och lägga till partners
går att öppna som administratör där alla projekt listas eller som projektledare då bara deras projekt syns
> Ny edit projekt partner klass.

- Java-Project-Management/src/ngo_2024/AvdelningMeny.form
- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
* Fältet töms när man klickar i det.
* När man trycker Enter i fältet körs sökmetoden.
> QoL-förbättringar för AvdelningMeny

- Java-Project-Management/src/ngo_2024/Huvudmeny.java
> En ny omruta. 

- Java-Project-Management/src/ngo_2024/AnstalldMeny.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
Styrt upp kommentarer och refaktoriserat lite kod.
* Delat upp radera-funktionen i en massa try-catch för att kunna ger mer detaljerade fel.
* Skrev om en funktion som hämtade ut anställda för en viss avdelning till en subquery istället för två SQL-satser.
* Försökt standardisera felmeddelanden och sett till att koden är korrekt indenterad med alt+shift+f. 
* Raderat dubblett-funktion
> AnställdMeny uppdaterad med mer homogena kommentarer, etc.

- Java-Project-Management/src/ngo_2024/AnstalldMeny.java
- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/EditAnstalld.form
- Java-Project-Management/src/ngo_2024/EditAnstalld.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
* Lagt till try-catch på många ställen.
* Standardiserat meddelanden. 
* AvdelningMeny blev också lite refaktoriserat för att kunna anropa en funktion från den från EditAnstalld
> Kommenterat upp EditAnstalld

- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/EditAvdelning.java
Flyttade en funktion till AvdelningMeny.
> Justering av dialogruta och indentering.

- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/EditAvdelning.java
- Java-Project-Management/src/ngo_2024/EditProjekt.java
- Java-Project-Management/src/ngo_2024/LandMeny.java
- Java-Project-Management/src/ngo_2024/ProjektMeny.java
Mindre justeringar trodde jag, men det finns någon konflikt. Jag löser den på en gång.
> Projekt refaktor

- Java-Project-Management/src/ngo_2024/EditStad.form
- Java-Project-Management/src/ngo_2024/EditStad.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.form
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
- Java-Project-Management/src/ngo_2024/StadMeny.java
* Kan nu skapa nya städer.
* Fixat till felmeddelanden
* Refaktoriserat några funktioner
* Lagt till Stad-meny under Administration
* Knapparna funkar också nu
> Stor uppdatering av Stad

- Java-Project-Management/src/ngo_2024/AvdelningMeny.java
- Java-Project-Management/src/ngo_2024/HandläggareProjektMeny.java
Insåg att jag missat denna. Nu har jag gått igenom alla felmeddelanden ....
Justerade en metod som hade lite många returns i sig.
> HandlaggareProjektMeny felmeddelanden

- Java-Project-Management/src/ngo_2024/EditStad.form
- Java-Project-Management/src/ngo_2024/EditStad.java
- Java-Project-Management/src/ngo_2024/StadMeny.form
- Java-Project-Management/src/ngo_2024/StadMeny.java
Uppdaterat till dispose när fönstret stängs.
> Buggfix i Stad

- Java-Project-Management/src/ngo_2024/ProjektMeny.java
' Uppdaterat SQL-satsen till en UNION-variant.
> Fix för projektchefer så de ser sina projekt

- Java-Project-Management/src/ngo_2024/Huvudmeny.form
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
- Java-Project-Management/src/ngo_2024/ProjektMeny.form
- Java-Project-Management/src/ngo_2024/ProjektMeny.java
Mina projekt visar nu både deltagande och projektledda projekt, Projektchefer får upp knapp att ändra projekt, OCH med kontroll om de är PL för projektet, annars kan de inte redigera!
Refaktoriserad huvudmeny, med alternativ under Projekt som bara projektchefer ser
> Projekt refaktorisering

- Java-Project-Management/src/ngo_2024/AnstalldMeny.java
- Java-Project-Management/src/ngo_2024/LandMeny.java
Lagt till param och return i kommentar...
> Land meny minifix

- Java-Project-Management/src/ngo_2024/AnstalldMeny.java
- Java-Project-Management/src/ngo_2024/Huvudmeny.java
tog bort två system-out-print av sqlfrågor
uppdaterade huvudmeny med fun fact
> Anstalld fix

- Java-Project-Management/src/ngo_2024/EditAnstalld.java
- Java-Project-Management/src/ngo_2024/InloggningMeny.java
- Java-Project-Management/src/ngo_2024/Validering.java
Bytt namn på kontrollen och lagt till den i återställ lösenord
> Epostkontroll

- Java-Project-Management/src/ngo_2024/InloggningMeny.form
- Java-Project-Management/src/ngo_2024/InloggningMeny.java
Tog bort "Vanlig användare". Gjort inloggning för Admin och Projch osynlig. Mindre justeringar
> [Låt stå] INLOGGNING sista innan inlämning

- Java-Project-Management/src/ngo_2024/EditAnstalld.java
- Java-Project-Management/src/ngo_2024/EditPartner.java
- Java-Project-Management/src/ngo_2024/EditProjekt.java
- Java-Project-Management/src/ngo_2024/Validering.java
Se rubrik. 
Bytt namn på datumFöreKontroll
> Telefonvalidering

- Java-Project-Management/src/ngo_2024/EditProjekt.form
- Java-Project-Management/src/ngo_2024/EditProjekt.java
- Java-Project-Management/src/ngo_2024/ProjektMeny.form
- Java-Project-Management/src/ngo_2024/ProjektMeny.java
Inte börjat kolla datum-lösningen än men ville få upp det befintliga inkl refaktorisering
> Projekt o edit projekt

- Java-Project-Management/src/ngo_2024/EditAnstalld.form
- Java-Project-Management/src/ngo_2024/EditAnstalld.java
* Ändrat så när man klickar på de olika boxarna inaktveras den andra om rutan är ifylld. Den andra rutan aktiveras om man klickar ur.
* Fixat så att konstrukturn även läser in detta för användarna från början.
> Checkbox-fix EditAnställd

- Java-Project-Management/src/ngo_2024/PartnerMeny.java
Skrivit om till en UNION-sats när projektpartners hämtas ut.
> Hämta ut projektpartners

- Java-Project-Management/src/ngo_2024/LandMeny.java
Fönstret uppdaterades inte automagiskt vid fokus
> Buggfix i LandMeny
